// AUTO-GENERATED by `npm run features:codegen` — do not edit by hand.
// Add a feature: create services/features/<X>/feature.manifest.ts then re-run.
// CI fails if this file is stale (`features:codegen:check`).

import type {FeatureManifest} from './featureManifest';
import {analyticsFeature} from '../features/Analytics/feature.manifest';
import {assetsFeature} from '../features/Assets/feature.manifest';
import {auditFeature} from '../features/Audit/feature.manifest';
import {bundleFeature} from '../features/Bundle/feature.manifest';
import {cartFeature} from '../features/Cart/feature.manifest';
import {customerAuthFeature} from '../features/CustomerAuth/feature.manifest';
import {featureFlagsFeature} from '../features/FeatureFlags/feature.manifest';
import {footerFeature} from '../features/Footer/feature.manifest';
import {inventoryFeature} from '../features/Inventory/feature.manifest';
import {languagesFeature} from '../features/Languages/feature.manifest';
import {mcpFeature} from '../features/Mcp/feature.manifest';
import {navigationFeature} from '../features/Navigation/feature.manifest';
import {observabilityFeature} from '../features/Observability/feature.manifest';
import {onboardingFeature} from '../features/Onboarding/feature.manifest';
import {ordersFeature} from '../features/Orders/feature.manifest';
import {permissionsFeature} from '../features/Permissions/feature.manifest';
import {platformFeature} from '../features/Platform/feature.manifest';
import {postsFeature} from '../features/Posts/feature.manifest';
import {presenceFeature} from '../features/Presence/feature.manifest';
import {productsFeature} from '../features/Products/feature.manifest';
import {publishingFeature} from '../features/Publishing/feature.manifest';
import {seoFeature} from '../features/Seo/feature.manifest';
import {serverRestartFeature} from '../features/ServerRestart/feature.manifest';
import {themesFeature} from '../features/Themes/feature.manifest';
import {usersFeature} from '../features/Users/feature.manifest';

export const featureRegistry: readonly FeatureManifest[] = [
    analyticsFeature,
    assetsFeature,
    auditFeature,
    bundleFeature,
    cartFeature,
    customerAuthFeature,
    featureFlagsFeature,
    footerFeature,
    inventoryFeature,
    languagesFeature,
    mcpFeature,
    navigationFeature,
    observabilityFeature,
    onboardingFeature,
    ordersFeature,
    permissionsFeature,
    platformFeature,
    postsFeature,
    presenceFeature,
    productsFeature,
    publishingFeature,
    seoFeature,
    serverRestartFeature,
    themesFeature,
    usersFeature,
];
