# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  mongodb:
    image: 'mongo:7.0'
    container_name: mongodb
    restart: always
#    ports:
#      - '27018:27017'
#    expose:
#      - 27018
    networks:
      - db
      - back-end
  server:
    container_name: server
    build:
      context: .
      dockerfile: ServerDockerfile
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:3000?query=%7B%0A%09sample%0A%7D%0A"]
      interval: 10s
    command: npm run standalone-graphql-docker
    networks:
      - db
      - back-end
    ports:
      - 3000:3000
    expose:
      - 3000
  app:
    container_name: front
    depends_on:
      - mongodb
      - server
    command: npm run start-docker
    build:
      context: .
      dockerfile: AppDockerfile
    environment:
      - BUILD_PORT=3000
    networks:
      - db
      - front-end
      - back-end
    ports:
      - 80:80
    expose:
      - 80
networks:
  front-end:
  db:
  back-end: