export enum EItemType {
    Text = "TEXT",
    RichText = "RICH_TEXT",
    Image = "IMAGE",
    Carousel = "CAROUSEL",
    Gallery = "GALLERY",
    Hero = "HERO",
    ProjectCard = "PROJECT_CARD",
    SkillPills = "SKILL_PILLS",
    Timeline = "TIMELINE",
    SocialLinks = "SOCIAL_LINKS",
    BlogFeed = "BLOG_FEED",
    List = "LIST",
    Services = "SERVICES",
    Testimonials = "TESTIMONIALS",
    StatsCard = "STATS_CARD",
    ProjectGrid = "PROJECT_GRID",
    Manifesto = "MANIFESTO",
    InquiryForm = "INQUIRY_FORM",
    DataModel = "DATA_MODEL",
    InfraTopology = "INFRA_TOPOLOGY",
    PipelineFlow = "PIPELINE_FLOW",
    RepoTree = "REPO_TREE",
    Empty = 'EMPTY',
}
export default EItemType