#!/usr/bin/env node
/**
 * Emit `services/infra/featureRegistry.generated.ts` — the explicit
 * static-import list of every feature manifest under
 * `services/features/<X>/feature.manifest.ts`.
 *
 * Why generate vs hand-maintain
 *   - Adding a feature is a one-folder operation: drop a manifest,
 *     re-run codegen, the registry picks it up.
 *   - The generated file is committed; consumers see real static
 *     imports so WebStorm / VS Code "Find Usages" walks all the way
 *     through the registry to the originating service classes.
 *   - CI runs `--check`: regenerate to a temp file, diff against the
 *     committed file, fail if different. A missed `npm run features:codegen`
 *     surfaces in PR review, not at runtime.
 *
 * Convention
 *   Each feature folder exports exactly one `*Feature` const matching
 *   `<lowerFirstFolderName>Feature`. The codegen reads the export name
 *   via a shallow regex (no full TS parse — keeps the script portable).
 */
import {existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync} from 'node:fs';
import * as path from 'node:path';
import {fileURLToPath} from 'node:url';

// tsx runs this as ESM; `__dirname` isn't defined in that scope, so
// reconstruct it from `import.meta.url` (the canonical Node ESM pattern).
const _filename = fileURLToPath(import.meta.url);
const _dirname = path.dirname(_filename);

const REPO_ROOT = path.resolve(_dirname, '..');
const FEATURES_DIR = path.join(REPO_ROOT, 'services', 'features');
const OUT_PATH = path.join(REPO_ROOT, 'services', 'infra', 'featureRegistry.generated.ts');
const RELATIVE_FROM_INFRA = '../features';

interface FoundManifest {
    folder: string;
    importPath: string;
    constName: string;
}

const HEADER = `// AUTO-GENERATED by \`npm run features:codegen\` — do not edit by hand.
// Add a feature: create services/features/<X>/feature.manifest.ts then re-run.
// CI fails if this file is stale (\`features:codegen:check\`).

`;

function findManifests(): FoundManifest[] {
    if (!existsSync(FEATURES_DIR)) return [];
    const out: FoundManifest[] = [];
    for (const entry of readdirSync(FEATURES_DIR).sort()) {
        const full = path.join(FEATURES_DIR, entry);
        if (!statSync(full).isDirectory()) continue;
        const candidates = [
            path.join(full, 'feature.manifest.ts'),
            path.join(full, 'feature.manifest.tsx'),
        ];
        const manifest = candidates.find(p => existsSync(p));
        if (!manifest) continue;
        const constName = readExportedConst(manifest);
        if (!constName) {
             
            console.error(`[codegen] ${manifest}: no \`export const <name>Feature\` found — skipping.`);
            continue;
        }
        // Path used by the import — relative to the registry file's directory.
        const importPath = `${RELATIVE_FROM_INFRA}/${entry}/feature.manifest`;
        out.push({folder: entry, importPath, constName});
    }
    return out;
}

function readExportedConst(file: string): string | null {
    const src = readFileSync(file, 'utf8');
    // Match `export const <name>Feature` where <name> is camelCase.
    // Case-insensitive on the suffix to tolerate "feature" vs "Feature".
    const m = src.match(/export\s+const\s+([a-z][A-Za-z0-9_]*Feature)\b/);
    return m ? m[1] : null;
}

function emit(found: FoundManifest[]): string {
    if (!found.length) {
        return `${HEADER}import type {FeatureManifest} from './featureManifest';\n\nexport const featureRegistry: readonly FeatureManifest[] = [];\n`;
    }
    const imports = found.map(f => `import {${f.constName}} from '${f.importPath}';`).join('\n');
    const list = found.map(f => `    ${f.constName},`).join('\n');
    return `${HEADER}import type {FeatureManifest} from './featureManifest';
${imports}

export const featureRegistry: readonly FeatureManifest[] = [
${list}
];
`;
}

function main(): void {
    const checkMode = process.argv.includes('--check');
    const found = findManifests();
    const next = emit(found);

    if (checkMode) {
        if (!existsSync(OUT_PATH)) {
             
            console.error(`[codegen] ${OUT_PATH} is missing. Run \`npm run features:codegen\`.`);
            process.exit(1);
        }
        const current = readFileSync(OUT_PATH, 'utf8');
        if (current !== next) {
             
            console.error('[codegen] featureRegistry.generated.ts is stale. Run `npm run features:codegen` and commit the result.');
            process.exit(1);
        }
        process.stdout.write(`[codegen] up to date (${found.length} features)\n`);
        return;
    }

    mkdirSync(path.dirname(OUT_PATH), {recursive: true});
    writeFileSync(OUT_PATH, next);
    process.stdout.write(`[codegen] wrote ${path.relative(REPO_ROOT, OUT_PATH)} (${found.length} features)\n`);
}

main();
