#!/usr/bin/env bash
# tools/mongo-bootstrap.sh — first-time MongoDB auth bootstrap (P5).
#
# Creates the root admin user (if not present) and a service-scoped
# `cms` user with `readWrite` on the application database, then writes
# the connection string to a 0600-perm file the operator copies into
# `.env`. Idempotent: re-running it after the users exist is a no-op.
#
# Usage (on the production droplet, from /opt/cms):
#     sudo bash tools/mongo-bootstrap.sh
#
# Env (all optional, sensible defaults):
#     MONGO_HOST=mongodb            # container name on the prod compose net
#     MONGO_PORT=27017
#     MONGO_DB=MAIN-DB
#     MONGO_INITDB_ROOT_USERNAME=root
#     MONGO_INITDB_ROOT_PASSWORD=…  # generated if absent
#     MONGO_APP_USER=cms
#     MONGO_APP_PASS=…              # generated if absent
#     MONGO_BOOTSTRAP_OUT=/opt/cms/secrets/mongo-bootstrap.env
#
# Security:
#   - When stdout is NOT a TTY (CI / piped), we never print passwords —
#     they only land in the 0600 output file.
#   - The output file is `chmod 600` and owned by the invoking user.
#   - This script does NOT call `docker compose up` for you. Run it
#     ONCE while Mongo is running but BEFORE setting `MONGO_USER` /
#     `MONGO_PASS` in the app's `.env` (otherwise the app would try to
#     auth as a user that doesn't exist yet and refuse to boot).
set -euo pipefail

MONGO_HOST="${MONGO_HOST:-mongodb}"
MONGO_PORT="${MONGO_PORT:-27017}"
MONGO_DB="${MONGO_DB:-MAIN-DB}"
ROOT_USER="${MONGO_INITDB_ROOT_USERNAME:-root}"
APP_USER="${MONGO_APP_USER:-cms}"
OUT_FILE="${MONGO_BOOTSTRAP_OUT:-/opt/cms/secrets/mongo-bootstrap.env}"

gen_pw() {
    # 32 chars, URL-safe-ish (drop / + = which would need URL encoding
    # in the connection string).
    openssl rand -base64 32 | tr -d '/+=\n' | cut -c1-32
}

ROOT_PASS="${MONGO_INITDB_ROOT_PASSWORD:-$(gen_pw)}"
APP_PASS="${MONGO_APP_PASS:-$(gen_pw)}"

mkdir -p "$(dirname "$OUT_FILE")"
chmod 700 "$(dirname "$OUT_FILE")" 2>/dev/null || true

# `mongo` is gone in 6+; production uses `mongosh`. Try both so the
# script works against the legacy 5.x image too.
SHELL_BIN="mongosh"
if ! docker exec mongodb sh -c "command -v $SHELL_BIN >/dev/null"; then
    SHELL_BIN="mongo"
fi

echo "[mongo-bootstrap] using $SHELL_BIN inside the mongodb container"

# Probe: can we reach Mongo without auth? If yes, we're on first boot
# (no users exist yet) — create the root user via `localhost exception`.
# If auth is already on, we expect ROOT_PASS to be the existing one and
# the createUser call below will run idempotently against $external.
docker exec -i mongodb $SHELL_BIN --quiet "mongodb://${MONGO_HOST}:${MONGO_PORT}/admin" <<EOF || true
db.createUser({
    user: "$ROOT_USER",
    pwd:  "$ROOT_PASS",
    roles: [{role: "root", db: "admin"}]
});
EOF

# Now create / refresh the app-scoped user. We log in as root for this
# step — works whether Mongo just enabled auth or had it on already.
docker exec -i mongodb $SHELL_BIN --quiet \
    "mongodb://${ROOT_USER}:${ROOT_PASS}@${MONGO_HOST}:${MONGO_PORT}/admin" <<EOF
try {
    db.getSiblingDB("admin").createUser({
        user: "$APP_USER",
        pwd:  "$APP_PASS",
        roles: [
            {role: "readWrite", db: "$MONGO_DB"},
            {role: "dbAdmin",   db: "$MONGO_DB"}
        ]
    });
    print("created $APP_USER");
} catch (e) {
    if (String(e).indexOf("already exists") >= 0) {
        db.getSiblingDB("admin").changeUserPassword("$APP_USER", "$APP_PASS");
        print("rotated $APP_USER password");
    } else { throw e; }
}
EOF

APP_URI="mongodb://${APP_USER}:${APP_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin"

umask 077
cat > "$OUT_FILE" <<EOF
# Generated by tools/mongo-bootstrap.sh on $(date -u +%FT%TZ)
# Copy these into /opt/cms/.env, then \`docker compose up -d\`.
MONGO_INITDB_ROOT_USERNAME=$ROOT_USER
MONGO_INITDB_ROOT_PASSWORD=$ROOT_PASS
MONGO_USER=$APP_USER
MONGO_PASS=$APP_PASS
MONGO_AUTH_SOURCE=admin
MONGODB_DB=$MONGO_DB
MONGODB_URI=$APP_URI
EOF
chmod 600 "$OUT_FILE"

if [ -t 1 ]; then
    echo "[mongo-bootstrap] credentials:"
    echo "  root user:  $ROOT_USER / $ROOT_PASS"
    echo "  app  user:  $APP_USER / $APP_PASS"
    echo "  app  URI :  $APP_URI"
    echo "[mongo-bootstrap] also written to $OUT_FILE (chmod 600)"
else
    echo "[mongo-bootstrap] credentials written to $OUT_FILE (chmod 600). Stdout is non-interactive — passwords NOT printed."
fi
